### ISSUE TITLE
Week 4 Milestone Tasks

### ISSUE THREAD

**Issue by michael-gelfand** [UBC-MDS/522_group_27#45]
Here are the required tasks for our milestone 4 implementation:
- [ ] Create Makefile to simplify analysis execution
- [ ] Update environment file
- [ ] Abstract some code from scripts to functions in a separate file, and write tests for those functions
